### ISSUE TITLE
Add filter field functionality for full text search in messages

### ISSUE THREAD

**Issue by tsykora** [infinispan/infispector#28]
Add filter field somewhere near to messages list for filtering. 
User can specify string like: CacheTopologyControlCommand; SingleRpcCommand or PutKeyValueCommand; etc..

Only messages containing this "string" will be filtered out and displayed on UI together with their count for further investigation. 

Chart will be redrawn reflecting ONLY flow of currently filtered messages.

**Comment by VratislavHais** [comment]
solved

**Comment by tsykora** [comment]
Solved, closing. Thanks!
