### ISSUE TITLE
Design and develop intelligent "historical" time slider for messages filtering

### ISSUE THREAD

**Issue by tsykora** [infinispan/infispector#31]
At the start, slider will cover (from left to right) the whole time frame. I.e. starting from the time of the first monitored message in druid and ending with a time of the last monitored message captured. 

The issue here is that we want to monitor longer time periods in the future of our project. Clusters can run an hour, a day... even more than that.

My idea is to have the whole range at the start and then -- be able to somehow ZOOM into more specific (smaller) time frames and be able to even select the range in the magnitude of milliseconds. 

E.g. At the start user could see that the whole cluster communication (captured) was happening between 5 PM and 6 PM a particular date. But we want to look only at the first minute, when the cluster was forming... Zoomable time slider will allow to select a portion of time from the start and zoom more, more and more until we are able to choose only the first 60 seconds. 

Later, after communication investigation, we want to know what was exactly happening just 10 milliseconds after the first message. We will be able to zoom more and select the first 10 milliseconds of communication. 

---> time frame goes to druid query, returning only messages from given time frame (functions are already prepared by @mciz). All messages will be shown and can be processed by other filter -- e.g. special type of messages, not all, etc.

**Comment by VratislavHais** [comment]
Already done by timeLine graph
